version: "3.3"
services:
  angular_backend:
    container_name: "angular_backend"
    expose:
     - "4200"
    ports:
     - "4203:4200"
    build: .
    command: ng serve --host 0.0.0.0
    volumes:
      - ./test/selenium-test:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]