version: "3.3"
services:
  angular_backend:
    container_name: "angular_backend"
    expose:
     - "9000"
    ports:
     - "9000:9000"
    build: .
    command: ng serve --port 9000 --host 0.0.0.0
    volumes:
      - ./test/selenium-test:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]